name: eShopOnWeb Build and Test

on: workflow_dispatch

env:
  RESOURCE_GROUP: rg-eshoponweb-region2
  LOCATION: westus3
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: bc6963eb-cb18-49c5-a4de-5c3fd94c2646
  WEBAPP_NAME: devops-webapp-region1-63787839

jobs:
  buildandtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      - name: Upload website artifact
        uses: actions/upload-artifact@v5
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      - name: Upload bicep template
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest

    environment:
      name: Development

    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v6
        with:
          name: dotnet-app
          path: dotnet-app

      - name: Download bicep template
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: >
            webAppName=${{ env.WEBAPP_NAME }}
            location=${{ env.LOCATION }}
          failOnStdErr: false

      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path dotnet-app/app.zip \
              --type zip
